pipeline {
    agent any
    stages {
		stage('clone_repo'){
	steps {
	git branch: 'seed_job_parallel', credentialsId: 'Muddu134-Github', url: 'git@github.com:Muddu134/Jenkins.git'
	}
	}
        stage('Build_App2') {
            
            steps{
                sh 'echo "The region is ${REGION}"'
                
            }
        }
        
        
    }
    
}