pipeline {
    agent any
    stages {
        stage(Build_App3) {
            
            steps{
                sh 'echo "The region is ${REGION}"'
                
            }
        }

    }
    
}